# Generated by Django 6.0 on 2026-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comments_media/'),
        ),
    ]
